"""session videos

Revision ID: edcd18a85b3f
Revises: c4a6ebab25f4
Create Date: 2026-09-23 20:10:56.672613+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "edcd18a85b3f"
down_revision: str | None = "c4a6ebab25f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_videos",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("external_event_id", sa.String(length=128), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_session_videos_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_session_videos_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_session_videos_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_videos_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_videos")),
    )
    op.create_index(
        op.f("ix_session_videos_organization_id"),
        "session_videos",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_videos_player_id"), "session_videos", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_session_videos_session_id"), "session_videos", ["session_id"], unique=False
    )
    op.create_index(
        "ix_session_videos_session_player",
        "session_videos",
        ["session_id", "player_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_session_videos_session_player", table_name="session_videos")
    op.drop_index(op.f("ix_session_videos_session_id"), table_name="session_videos")
    op.drop_index(op.f("ix_session_videos_player_id"), table_name="session_videos")
    op.drop_index(op.f("ix_session_videos_organization_id"), table_name="session_videos")
    op.drop_table("session_videos")
    # ### end Alembic commands ###
