"""initial schema

Revision ID: 9edd112c7ebf
Revises:
Create Date: 2026-09-13 02:10:43.157491+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9edd112c7ebf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "metric_definitions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "PITCHING",
                "HITTING",
                "THROWING",
                "TRAINING",
                name="metric_category",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "event_source",
            sa.Enum("PITCH", "HIT", name="event_source", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column(
            "aggregation",
            sa.Enum(
                "MAX",
                "MIN",
                "AVG",
                "COUNT",
                "SUM",
                "RATE",
                name="aggregation",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "record_direction",
            sa.Enum(
                "HIGHER_IS_BETTER",
                "LOWER_IS_BETTER",
                "NONE",
                name="record_direction",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_type",
            sa.Enum("FLOAT", "INTEGER", name="metric_data_type", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("display_precision", sa.Integer(), nullable=False),
        sa.Column("min_sample_size", sa.Integer(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("calculation_version", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_headline", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_metric_definitions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_definitions")),
        sa.UniqueConstraint("organization_id", "key", name="uq_metric_definitions_key"),
    )
    op.create_index(
        "ix_metric_definitions_org_category",
        "metric_definitions",
        ["organization_id", "category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_definitions_organization_id"),
        "metric_definitions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "players",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("preferred_name", sa.String(length=100), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("graduation_year", sa.Integer(), nullable=True),
        sa.Column("position", sa.String(length=32), nullable=True),
        sa.Column(
            "bats", sa.Enum("L", "R", "S", name="bats", native_enum=False, length=64), nullable=True
        ),
        sa.Column(
            "throws",
            sa.Enum("L", "R", "S", name="throws", native_enum=False, length=64),
            nullable=True,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_players_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
    )
    op.create_index(
        op.f("ix_players_organization_id"), "players", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_players_organization_id_active", "players", ["organization_id", "active"], unique=False
    )
    op.create_index(
        "ix_players_organization_id_last_name",
        "players",
        ["organization_id", "last_name"],
        unique=False,
    )
    op.create_table(
        "raw_imports",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("import_type", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "PROCESSING",
                "SUCCESS",
                "PARTIAL",
                "FAILED",
                "SKIPPED_DUPLICATE",
                name="import_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_status",
            sa.Enum("PRELIMINARY", "VERIFIED", name="source_status", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_total", sa.Integer(), nullable=False),
        sa.Column("rows_accepted", sa.Integer(), nullable=False),
        sa.Column("rows_rejected", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_raw_imports_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_imports")),
        sa.UniqueConstraint(
            "organization_id", "provider", "checksum", name="uq_raw_imports_checksum"
        ),
    )
    op.create_index(
        "ix_raw_imports_org_created_at",
        "raw_imports",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_raw_imports_org_status", "raw_imports", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_raw_imports_organization_id"), "raw_imports", ["organization_id"], unique=False
    )
    op.create_table(
        "external_metric_mappings",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("metric_definition_id", sa.UUID(), nullable=False),
        sa.Column("destination", sa.String(length=32), nullable=False),
        sa.Column("destination_field", sa.String(length=160), nullable=False),
        sa.Column("destination_unit", sa.String(length=16), nullable=True),
        sa.Column("destination_precision", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["metric_definitions.id"],
            name=op.f("fk_external_metric_mappings_metric_definition_id_metric_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_external_metric_mappings_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_metric_mappings")),
        sa.UniqueConstraint(
            "organization_id",
            "destination",
            "metric_definition_id",
            name="uq_metric_mapping_destination_metric",
        ),
    )
    op.create_index(
        op.f("ix_external_metric_mappings_metric_definition_id"),
        "external_metric_mappings",
        ["metric_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_metric_mappings_organization_id"),
        "external_metric_mappings",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "external_player_identities",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("external_display_name", sa.String(length=200), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_external_player_identities_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_external_player_identities_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_player_identities")),
        sa.UniqueConstraint(
            "organization_id", "provider", "external_id", name="uq_external_identity_provider_id"
        ),
    )
    op.create_index(
        "ix_external_identities_player_provider",
        "external_player_identities",
        ["player_id", "provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_player_identities_organization_id"),
        "external_player_identities",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_player_identities_player_id"),
        "external_player_identities",
        ["player_id"],
        unique=False,
    )
    op.create_table(
        "import_issues",
        sa.Column("raw_import_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=True),
        sa.Column(
            "code",
            sa.Enum(
                "SCHEMA_UNKNOWN",
                "MISSING_REQUIRED_FIELD",
                "INVALID_VALUE",
                "INVALID_UNIT",
                "PLAYER_UNRESOLVED",
                "AMBIGUOUS_SESSION",
                name="import_issue_code",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("field", sa.String(length=128), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raw_import_id"],
            ["raw_imports.id"],
            name=op.f("fk_import_issues_raw_import_id_raw_imports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_issues")),
    )
    op.create_index(
        "ix_import_issues_import_code", "import_issues", ["raw_import_id", "code"], unique=False
    )
    op.create_index(
        op.f("ix_import_issues_raw_import_id"), "import_issues", ["raw_import_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_session_id", sa.String(length=128), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("session_type", sa.String(length=48), nullable=True),
        sa.Column("venue", sa.String(length=120), nullable=True),
        sa.Column(
            "source_status",
            sa.Enum("PRELIMINARY", "VERIFIED", name="source_status", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_import_id", sa.UUID(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sessions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_import_id"],
            ["raw_imports.id"],
            name=op.f("fk_sessions_raw_import_id_raw_imports"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint(
            "organization_id",
            "provider",
            "external_session_id",
            name="uq_sessions_provider_external_id",
        ),
    )
    op.create_index(
        "ix_sessions_org_date", "sessions", ["organization_id", "session_date"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_organization_id"), "sessions", ["organization_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("auth_provider", sa.String(length=32), nullable=False),
        sa.Column("auth_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "COACH", "PLAYER", name="role", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_users_player_id_players"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("auth_provider", "auth_subject", name="uq_users_auth_identity"),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_index(
        "ix_users_organization_id_role", "users", ["organization_id", "role"], unique=False
    )
    op.create_index(op.f("ix_users_player_id"), "users", ["player_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.String(length=200), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "PLAYER_MAPPING_CREATED",
                "PLAYER_MAPPING_CHANGED",
                "METRIC_CREATED",
                "METRIC_CHANGED",
                "PR_OVERRIDDEN",
                "FUTURES_SYNC_MANUALLY_CONFIRMED",
                "IMPORT_REPROCESSED",
                name="audit_action",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_logs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_org_created", "audit_logs", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_target", "audit_logs", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "identity_resolution_items",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("external_display_name", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "UNRESOLVED",
                "RESOLVED",
                "IGNORED",
                name="identity_resolution_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("first_seen_import_id", sa.UUID(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_player_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_import_id"],
            ["raw_imports.id"],
            name=op.f("fk_identity_resolution_items_first_seen_import_id_raw_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_identity_resolution_items_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
            name=op.f("fk_identity_resolution_items_resolved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_player_id"],
            ["players.id"],
            name=op.f("fk_identity_resolution_items_resolved_player_id_players"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_resolution_items")),
        sa.UniqueConstraint(
            "organization_id", "provider", "external_id", name="uq_identity_resolution_provider_id"
        ),
    )
    op.create_index(
        op.f("ix_identity_resolution_items_organization_id"),
        "identity_resolution_items",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_identity_resolution_org_status",
        "identity_resolution_items",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "metric_observations",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("metric_definition_id", sa.UUID(), nullable=False),
        sa.Column(
            "period",
            sa.Enum(
                "SESSION",
                "DAY",
                "WEEK",
                "MONTH",
                "ALL_TIME",
                name="period",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column(
            "source_status",
            sa.Enum("PRELIMINARY", "VERIFIED", name="source_status", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("calculation_version", sa.Integer(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["metric_definitions.id"],
            name=op.f("fk_metric_observations_metric_definition_id_metric_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_metric_observations_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_metric_observations_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_metric_observations_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_observations")),
        sa.UniqueConstraint(
            "player_id",
            "metric_definition_id",
            "period",
            "period_start",
            "session_id",
            "calculation_version",
            name="uq_metric_observations_scope",
        ),
    )
    op.create_index(
        "ix_metric_obs_org_period",
        "metric_observations",
        ["organization_id", "period_start"],
        unique=False,
    )
    op.create_index(
        "ix_metric_obs_player_metric_period",
        "metric_observations",
        ["player_id", "metric_definition_id", "period_start"],
        unique=False,
    )
    op.create_index("ix_metric_obs_session", "metric_observations", ["session_id"], unique=False)
    op.create_index(
        op.f("ix_metric_observations_metric_definition_id"),
        "metric_observations",
        ["metric_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_organization_id"),
        "metric_observations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_observations_player_id"), "metric_observations", ["player_id"], unique=False
    )
    op.create_table(
        "personal_record_events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("metric_definition_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("previous_value", sa.Float(), nullable=True),
        sa.Column("new_value", sa.Float(), nullable=False),
        sa.Column("delta", sa.Float(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("achieved_on", sa.Date(), nullable=False),
        sa.Column("achieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "source_status",
            sa.Enum("PRELIMINARY", "VERIFIED", name="source_status", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("calculation_version", sa.Integer(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["metric_definitions.id"],
            name=op.f("fk_personal_record_events_metric_definition_id_metric_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_personal_record_events_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_personal_record_events_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_personal_record_events_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personal_record_events")),
        sa.UniqueConstraint(
            "player_id",
            "metric_definition_id",
            "session_id",
            name="uq_pr_events_player_metric_session",
        ),
    )
    op.create_index(
        op.f("ix_personal_record_events_metric_definition_id"),
        "personal_record_events",
        ["metric_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_record_events_organization_id"),
        "personal_record_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_record_events_player_id"),
        "personal_record_events",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_record_events_session_id"),
        "personal_record_events",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "ix_pr_events_org_achieved",
        "personal_record_events",
        ["organization_id", "achieved_on"],
        unique=False,
    )
    op.create_index(
        "ix_pr_events_player_metric",
        "personal_record_events",
        ["player_id", "metric_definition_id"],
        unique=False,
    )
    op.create_table(
        "personal_records",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("metric_definition_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("achieved_on", sa.Date(), nullable=False),
        sa.Column("achieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "source_status",
            sa.Enum("PRELIMINARY", "VERIFIED", name="source_status", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("calculation_version", sa.Integer(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_manual_override", sa.Boolean(), nullable=False),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["metric_definitions.id"],
            name=op.f("fk_personal_records_metric_definition_id_metric_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_personal_records_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_personal_records_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_personal_records_session_id_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personal_records")),
        sa.UniqueConstraint(
            "player_id", "metric_definition_id", name="uq_personal_records_player_metric"
        ),
    )
    op.create_index(
        op.f("ix_personal_records_metric_definition_id"),
        "personal_records",
        ["metric_definition_id"],
        unique=False,
    )
    op.create_index(
        "ix_personal_records_org_achieved",
        "personal_records",
        ["organization_id", "achieved_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_records_organization_id"),
        "personal_records",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_records_player_id"), "personal_records", ["player_id"], unique=False
    )
    op.create_table(
        "pitch_events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("external_event_id", sa.String(length=128), nullable=False),
        sa.Column("pitch_number", sa.Integer(), nullable=True),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pitch_type", sa.String(length=32), nullable=True),
        sa.Column("auto_pitch_type", sa.String(length=32), nullable=True),
        sa.Column("velocity_mph", sa.Float(), nullable=True),
        sa.Column("spin_rate_rpm", sa.Float(), nullable=True),
        sa.Column("spin_axis_deg", sa.Float(), nullable=True),
        sa.Column("horizontal_break_in", sa.Float(), nullable=True),
        sa.Column("vertical_break_in", sa.Float(), nullable=True),
        sa.Column("release_height_ft", sa.Float(), nullable=True),
        sa.Column("release_side_ft", sa.Float(), nullable=True),
        sa.Column("extension_ft", sa.Float(), nullable=True),
        sa.Column("plate_location_height_ft", sa.Float(), nullable=True),
        sa.Column("plate_location_side_ft", sa.Float(), nullable=True),
        sa.Column("vertical_approach_angle_deg", sa.Float(), nullable=True),
        sa.Column("horizontal_approach_angle_deg", sa.Float(), nullable=True),
        sa.Column("pitch_call", sa.String(length=32), nullable=True),
        sa.Column("is_strike", sa.Boolean(), nullable=True),
        sa.Column("training_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "source_status",
            sa.Enum("PRELIMINARY", "VERIFIED", name="source_status", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("raw_import_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_pitch_events_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_pitch_events_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_import_id"],
            ["raw_imports.id"],
            name=op.f("fk_pitch_events_raw_import_id_raw_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_pitch_events_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pitch_events")),
        sa.UniqueConstraint(
            "session_id", "external_event_id", name="uq_pitch_events_session_event"
        ),
    )
    op.create_index(
        "ix_pitch_events_org_event_at",
        "pitch_events",
        ["organization_id", "event_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pitch_events_organization_id"), "pitch_events", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_pitch_events_player_event_at", "pitch_events", ["player_id", "event_at"], unique=False
    )
    op.create_index(op.f("ix_pitch_events_player_id"), "pitch_events", ["player_id"], unique=False)
    op.create_index(
        "ix_pitch_events_player_pitch_type",
        "pitch_events",
        ["player_id", "pitch_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pitch_events_session_id"), "pitch_events", ["session_id"], unique=False
    )
    op.create_index(
        "ix_pitch_events_training_context",
        "pitch_events",
        ["training_context"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "hit_events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("pitch_event_id", sa.UUID(), nullable=True),
        sa.Column("external_event_id", sa.String(length=128), nullable=False),
        sa.Column("swing_number", sa.Integer(), nullable=True),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_velocity_mph", sa.Float(), nullable=True),
        sa.Column("launch_angle_deg", sa.Float(), nullable=True),
        sa.Column("launch_direction_deg", sa.Float(), nullable=True),
        sa.Column("distance_ft", sa.Float(), nullable=True),
        sa.Column("hang_time_s", sa.Float(), nullable=True),
        sa.Column("hit_spin_rate_rpm", sa.Float(), nullable=True),
        sa.Column("contact_position_x_ft", sa.Float(), nullable=True),
        sa.Column("contact_position_y_ft", sa.Float(), nullable=True),
        sa.Column("contact_position_z_ft", sa.Float(), nullable=True),
        sa.Column("batted_ball_type", sa.String(length=32), nullable=True),
        sa.Column("training_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "source_status",
            sa.Enum("PRELIMINARY", "VERIFIED", name="source_status", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("raw_import_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_hit_events_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pitch_event_id"],
            ["pitch_events.id"],
            name=op.f("fk_hit_events_pitch_event_id_pitch_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_hit_events_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_import_id"],
            ["raw_imports.id"],
            name=op.f("fk_hit_events_raw_import_id_raw_imports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_hit_events_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hit_events")),
        sa.UniqueConstraint("session_id", "external_event_id", name="uq_hit_events_session_event"),
    )
    op.create_index(
        "ix_hit_events_org_event_at", "hit_events", ["organization_id", "event_at"], unique=False
    )
    op.create_index(
        op.f("ix_hit_events_organization_id"), "hit_events", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_hit_events_player_event_at", "hit_events", ["player_id", "event_at"], unique=False
    )
    op.create_index(op.f("ix_hit_events_player_id"), "hit_events", ["player_id"], unique=False)
    op.create_index(op.f("ix_hit_events_session_id"), "hit_events", ["session_id"], unique=False)
    op.create_index(
        "ix_hit_events_training_context",
        "hit_events",
        ["training_context"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "sync_jobs",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("metric_definition_id", sa.UUID(), nullable=False),
        sa.Column("personal_record_event_id", sa.UUID(), nullable=True),
        sa.Column("destination", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("destination_field", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SYNCED",
                "FAILED",
                "MANUAL_REQUIRED",
                name="sync_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_user_id"],
            ["users.id"],
            name=op.f("fk_sync_jobs_completed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["metric_definitions.id"],
            name=op.f("fk_sync_jobs_metric_definition_id_metric_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sync_jobs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["personal_record_event_id"],
            ["personal_record_events.id"],
            name=op.f("fk_sync_jobs_personal_record_event_id_personal_record_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_sync_jobs_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_jobs")),
        sa.UniqueConstraint(
            "player_id",
            "metric_definition_id",
            "destination",
            "personal_record_event_id",
            name="uq_sync_jobs_target",
        ),
    )
    op.create_index(
        op.f("ix_sync_jobs_metric_definition_id"),
        "sync_jobs",
        ["metric_definition_id"],
        unique=False,
    )
    op.create_index(
        "ix_sync_jobs_org_status", "sync_jobs", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_sync_jobs_organization_id"), "sync_jobs", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_sync_jobs_player_id"), "sync_jobs", ["player_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_jobs_player_id"), table_name="sync_jobs")
    op.drop_index(op.f("ix_sync_jobs_organization_id"), table_name="sync_jobs")
    op.drop_index("ix_sync_jobs_org_status", table_name="sync_jobs")
    op.drop_index(op.f("ix_sync_jobs_metric_definition_id"), table_name="sync_jobs")
    op.drop_table("sync_jobs")
    op.drop_index("ix_hit_events_training_context", table_name="hit_events", postgresql_using="gin")
    op.drop_index(op.f("ix_hit_events_session_id"), table_name="hit_events")
    op.drop_index(op.f("ix_hit_events_player_id"), table_name="hit_events")
    op.drop_index("ix_hit_events_player_event_at", table_name="hit_events")
    op.drop_index(op.f("ix_hit_events_organization_id"), table_name="hit_events")
    op.drop_index("ix_hit_events_org_event_at", table_name="hit_events")
    op.drop_table("hit_events")
    op.drop_index(
        "ix_pitch_events_training_context", table_name="pitch_events", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_pitch_events_session_id"), table_name="pitch_events")
    op.drop_index("ix_pitch_events_player_pitch_type", table_name="pitch_events")
    op.drop_index(op.f("ix_pitch_events_player_id"), table_name="pitch_events")
    op.drop_index("ix_pitch_events_player_event_at", table_name="pitch_events")
    op.drop_index(op.f("ix_pitch_events_organization_id"), table_name="pitch_events")
    op.drop_index("ix_pitch_events_org_event_at", table_name="pitch_events")
    op.drop_table("pitch_events")
    op.drop_index(op.f("ix_personal_records_player_id"), table_name="personal_records")
    op.drop_index(op.f("ix_personal_records_organization_id"), table_name="personal_records")
    op.drop_index("ix_personal_records_org_achieved", table_name="personal_records")
    op.drop_index(op.f("ix_personal_records_metric_definition_id"), table_name="personal_records")
    op.drop_table("personal_records")
    op.drop_index("ix_pr_events_player_metric", table_name="personal_record_events")
    op.drop_index("ix_pr_events_org_achieved", table_name="personal_record_events")
    op.drop_index(op.f("ix_personal_record_events_session_id"), table_name="personal_record_events")
    op.drop_index(op.f("ix_personal_record_events_player_id"), table_name="personal_record_events")
    op.drop_index(
        op.f("ix_personal_record_events_organization_id"), table_name="personal_record_events"
    )
    op.drop_index(
        op.f("ix_personal_record_events_metric_definition_id"), table_name="personal_record_events"
    )
    op.drop_table("personal_record_events")
    op.drop_index(op.f("ix_metric_observations_player_id"), table_name="metric_observations")
    op.drop_index(op.f("ix_metric_observations_organization_id"), table_name="metric_observations")
    op.drop_index(
        op.f("ix_metric_observations_metric_definition_id"), table_name="metric_observations"
    )
    op.drop_index("ix_metric_obs_session", table_name="metric_observations")
    op.drop_index("ix_metric_obs_player_metric_period", table_name="metric_observations")
    op.drop_index("ix_metric_obs_org_period", table_name="metric_observations")
    op.drop_table("metric_observations")
    op.drop_index("ix_identity_resolution_org_status", table_name="identity_resolution_items")
    op.drop_index(
        op.f("ix_identity_resolution_items_organization_id"), table_name="identity_resolution_items"
    )
    op.drop_table("identity_resolution_items")
    op.drop_index("ix_audit_logs_target", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_org_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_player_id"), table_name="users")
    op.drop_index("ix_users_organization_id_role", table_name="users")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_sessions_organization_id"), table_name="sessions")
    op.drop_index("ix_sessions_org_date", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_import_issues_raw_import_id"), table_name="import_issues")
    op.drop_index("ix_import_issues_import_code", table_name="import_issues")
    op.drop_table("import_issues")
    op.drop_index(
        op.f("ix_external_player_identities_player_id"), table_name="external_player_identities"
    )
    op.drop_index(
        op.f("ix_external_player_identities_organization_id"),
        table_name="external_player_identities",
    )
    op.drop_index("ix_external_identities_player_provider", table_name="external_player_identities")
    op.drop_table("external_player_identities")
    op.drop_index(
        op.f("ix_external_metric_mappings_organization_id"), table_name="external_metric_mappings"
    )
    op.drop_index(
        op.f("ix_external_metric_mappings_metric_definition_id"),
        table_name="external_metric_mappings",
    )
    op.drop_table("external_metric_mappings")
    op.drop_index(op.f("ix_raw_imports_organization_id"), table_name="raw_imports")
    op.drop_index("ix_raw_imports_org_status", table_name="raw_imports")
    op.drop_index("ix_raw_imports_org_created_at", table_name="raw_imports")
    op.drop_table("raw_imports")
    op.drop_index("ix_players_organization_id_last_name", table_name="players")
    op.drop_index("ix_players_organization_id_active", table_name="players")
    op.drop_index(op.f("ix_players_organization_id"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_metric_definitions_organization_id"), table_name="metric_definitions")
    op.drop_index("ix_metric_definitions_org_category", table_name="metric_definitions")
    op.drop_table("metric_definitions")
    op.drop_table("organizations")
    # ### end Alembic commands ###
