"""pitch events carry a batter and swing result

Revision ID: c4a6ebab25f4
Revises: 9edd112c7ebf
Create Date: 2026-09-23 20:04:00.665798+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c4a6ebab25f4"
down_revision: str | None = "9edd112c7ebf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pitch_events", sa.Column("batter_id", sa.UUID(), nullable=True))
    op.add_column(
        "pitch_events",
        sa.Column(
            "swing_result",
            sa.Enum(
                "TAKEN", "SWING_MISS", "IN_PLAY", name="swing_result", native_enum=False, length=64
            ),
            nullable=True,
        ),
    )
    op.alter_column("pitch_events", "player_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(
        "ix_pitch_events_batter_event_at", "pitch_events", ["batter_id", "event_at"], unique=False
    )
    op.create_index(op.f("ix_pitch_events_batter_id"), "pitch_events", ["batter_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_pitch_events_batter_id_players"),
        "pitch_events",
        "players",
        ["batter_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # Written by hand: Alembic does not autogenerate CHECK constraints. A
    # tracked pitch with neither a pitcher nor a batter belongs to nobody and
    # could never be shown to anyone.
    op.create_check_constraint(
        "has_an_athlete",  # the naming convention prefixes ck_pitch_events_
        "pitch_events",
        "player_id IS NOT NULL OR batter_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("has_an_athlete", "pitch_events", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_pitch_events_batter_id_players"), "pitch_events", type_="foreignkey"
    )
    op.drop_index(op.f("ix_pitch_events_batter_id"), table_name="pitch_events")
    op.drop_index("ix_pitch_events_batter_event_at", table_name="pitch_events")
    op.alter_column("pitch_events", "player_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("pitch_events", "swing_result")
    op.drop_column("pitch_events", "batter_id")
    # ### end Alembic commands ###
