/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/dashboard/today": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Today */
    get: operations["today_api_v1_dashboard_today_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/identity/unresolved": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Unresolved
     * @description Vendor athletes awaiting a human decision.
     */
    get: operations["list_unresolved_api_v1_identity_unresolved_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/identity/unresolved/{item_id}/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resolve Identity
     * @description Map a vendor athlete to one of our players, and recover their held data.
     *
     *     Admin-only and audited: this decision determines whose data is whose, and it
     *     is the one place a mistake would attribute one athlete's numbers to another.
     *
     *     Events held back for this athlete are recovered by **reprocessing** the
     *     affected imports from their archived source bytes -- never by back-filling
     *     rows by hand. The recovered data therefore goes through exactly the same
     *     validated pipeline as a first ingest, and stays idempotent.
     */
    post: operations["resolve_identity_api_v1_identity_unresolved__item_id__resolve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Imports */
    get: operations["list_imports_api_v1_imports_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/trackman/csv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload Trackman Csv
     * @description Ingest a TrackMan CSV export.
     *
     *     Re-uploading the same file is safe and explicitly reported as a duplicate
     *     rather than silently creating a second copy of the session.
     */
    post: operations["upload_trackman_csv_api_v1_imports_trackman_csv_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/{import_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Import
     * @description One import with its rejected rows, so nothing is silently discarded.
     */
    get: operations["get_import_api_v1_imports__import_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/{import_id}/reprocess": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reprocess Import
     * @description Re-run a stored import from its archived source bytes.
     *
     *     Used after mapping a previously-unknown athlete, and after a parser or
     *     metric change. Audited, because it rewrites athlete-facing numbers.
     */
    post: operations["reprocess_import_api_v1_imports__import_id__reprocess_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/integrations/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Integration Status
     * @description Operational health. Broken automation is shown, never hidden.
     */
    get: operations["integration_status_api_v1_integrations_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations["get_me_api_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Overview */
    get: operations["my_overview_api_v1_me_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/prs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Records */
    get: operations["my_records_api_v1_me_prs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Sessions */
    get: operations["my_sessions_api_v1_me_sessions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Metrics
     * @description The organization's metric catalog.
     *
     *     The dashboard reads this rather than hardcoding metric names, so changing
     *     the metric set is a data change, not a frontend deployment.
     */
    get: operations["list_metrics_api_v1_metrics_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/players": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Players
     * @description Search the roster. Staff only -- a player has no roster.
     */
    get: operations["list_players_api_v1_players_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/players/{player_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Player */
    get: operations["get_player_api_v1_players__player_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/players/{player_id}/metrics/{metric_key}/series": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Metric Series
     * @description Session-by-session progression for one metric.
     */
    get: operations["get_metric_series_api_v1_players__player_id__metrics__metric_key__series_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/players/{player_id}/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Overview
     * @description Headline metrics, their movement over the window, and current records.
     */
    get: operations["get_overview_api_v1_players__player_id__overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/players/{player_id}/prs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Personal Records */
    get: operations["get_personal_records_api_v1_players__player_id__prs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/players/{player_id}/prs/{metric_key}/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Record History
     * @description The full progression -- when each record was set, and by how much.
     */
    get: operations["get_record_history_api_v1_players__player_id__prs__metric_key__history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/players/{player_id}/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Sessions */
    get: operations["get_sessions_api_v1_players__player_id__sessions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/prs/recent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Recent Records
     * @description Newest records across the organization -- the feed a coach scans first.
     */
    get: operations["recent_records_api_v1_prs_recent_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Sessions */
    get: operations["list_sessions_api_v1_sessions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sync/futures/pending": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Pending Futures Updates */
    get: operations["pending_futures_updates_api_v1_sync_futures_pending_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sync/futures/{job_id}/mark-updated": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark Updated
     * @description Confirm that a coach entered the value into Futures by hand.
     *
     *     Audited: this is the only evidence we will have that the external system
     *     was actually updated.
     */
    post: operations["mark_updated_api_v1_sync_futures__job_id__mark_updated_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness plus a real database round-trip.
     *
     *     Cloud Run will route traffic to an instance that answers here, so a
     *     healthy reply that cannot reach Postgres would be worse than useless.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Aggregation
     * @enum {string}
     */
    Aggregation: "MAX" | "MIN" | "AVG" | "COUNT" | "SUM" | "RATE";
    /** Body_upload_trackman_csv_api_v1_imports_trackman_csv_post */
    Body_upload_trackman_csv_api_v1_imports_trackman_csv_post: {
      /** File */
      file: string;
    };
    /** CurrentUser */
    CurrentUser: {
      /** Display Name */
      display_name: string;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
      /** Organization Name */
      organization_name: string;
      /** Player Id */
      player_id?: string | null;
      role: components["schemas"]["Role"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthOut */
    HealthOut: {
      /** Database */
      database: string;
      /** Environment */
      environment: string;
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /** ImportDetailOut */
    ImportDetailOut: {
      /** Completed At */
      completed_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error Message */
      error_message: string | null;
      /** Filename */
      filename: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Import Metadata */
      import_metadata?: {
        [key: string]: unknown;
      };
      /** Import Type */
      import_type: string;
      /** Issues */
      issues?: components["schemas"]["ImportIssueOut"][];
      /** Provider */
      provider: string;
      /** Rows Accepted */
      rows_accepted: number;
      /** Rows Rejected */
      rows_rejected: number;
      /** Rows Total */
      rows_total: number;
      source_status: components["schemas"]["SourceStatus"];
      status: components["schemas"]["ImportStatus"];
    };
    /**
     * ImportIssueCode
     * @description Machine-readable reasons a row or file was rejected or flagged.
     * @enum {string}
     */
    ImportIssueCode:
      | "SCHEMA_UNKNOWN"
      | "MISSING_REQUIRED_FIELD"
      | "INVALID_VALUE"
      | "INVALID_UNIT"
      | "PLAYER_UNRESOLVED"
      | "AMBIGUOUS_SESSION";
    /** ImportIssueOut */
    ImportIssueOut: {
      code: components["schemas"]["ImportIssueCode"];
      /** Field */
      field: string | null;
      /** Message */
      message: string;
      /** Row Number */
      row_number: number | null;
    };
    /** ImportOut */
    ImportOut: {
      /** Completed At */
      completed_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error Message */
      error_message: string | null;
      /** Filename */
      filename: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Import Metadata */
      import_metadata?: {
        [key: string]: unknown;
      };
      /** Import Type */
      import_type: string;
      /** Provider */
      provider: string;
      /** Rows Accepted */
      rows_accepted: number;
      /** Rows Rejected */
      rows_rejected: number;
      /** Rows Total */
      rows_total: number;
      source_status: components["schemas"]["SourceStatus"];
      status: components["schemas"]["ImportStatus"];
    };
    /** ImportResultOut */
    ImportResultOut: {
      /** Error Message */
      error_message?: string | null;
      /** Hit Events */
      hit_events: number;
      /** Is Duplicate */
      is_duplicate: boolean;
      /** Metric Observations */
      metric_observations: number;
      /** New Personal Records */
      new_personal_records: number;
      /** Pitch Events */
      pitch_events: number;
      /**
       * Raw Import Id
       * Format: uuid
       */
      raw_import_id: string;
      /** Rows Accepted */
      rows_accepted: number;
      /** Rows Rejected */
      rows_rejected: number;
      /** Rows Total */
      rows_total: number;
      /** Sessions Created */
      sessions_created: number;
      /** Sessions Updated */
      sessions_updated: number;
      /** Status */
      status: string;
      /** Sync Jobs Queued */
      sync_jobs_queued: number;
      /** Unresolved Players */
      unresolved_players: string[];
    };
    /**
     * ImportStatus
     * @description Lifecycle of a single ingestion attempt.
     * @enum {string}
     */
    ImportStatus:
      "RECEIVED" | "PROCESSING" | "SUCCESS" | "PARTIAL" | "FAILED" | "SKIPPED_DUPLICATE";
    /** IntegrationHealthOut */
    IntegrationHealthOut: {
      /** Failed Imports 7D */
      failed_imports_7d: number;
      /** Futures Updates Pending */
      futures_updates_pending: number;
      /** Last Import Status */
      last_import_status: string | null;
      /** Last Successful Import At */
      last_successful_import_at: string | null;
      /** Provider */
      provider: string;
      /** Sessions Awaiting Verification */
      sessions_awaiting_verification: number;
      /** Unresolved Players */
      unresolved_players: number;
    };
    /**
     * MetricCategory
     * @enum {string}
     */
    MetricCategory: "PITCHING" | "HITTING" | "THROWING" | "TRAINING";
    /** MetricComparison */
    MetricComparison: {
      /** Current */
      current: number | null;
      /** Current Sample */
      current_sample: number;
      current_source_status?: components["schemas"]["SourceStatus"] | null;
      /** Delta */
      delta: number | null;
      /** Percent Change */
      percent_change: number | null;
      /** Previous */
      previous: number | null;
      /** Previous Sample */
      previous_sample: number;
      previous_source_status?: components["schemas"]["SourceStatus"] | null;
    };
    /** MetricDefinitionOut */
    MetricDefinitionOut: {
      aggregation: components["schemas"]["Aggregation"];
      /** Calculation Version */
      calculation_version: number;
      category: components["schemas"]["MetricCategory"];
      /** Description */
      description?: string | null;
      /** Display Name */
      display_name: string;
      /** Display Precision */
      display_precision: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Headline */
      is_headline: boolean;
      /** Key */
      key: string;
      /** Min Sample Size */
      min_sample_size: number;
      record_direction: components["schemas"]["RecordDirection"];
      /** Unit */
      unit: string;
    };
    /** MetricSeriesOut */
    MetricSeriesOut: {
      definition: components["schemas"]["MetricDefinitionOut"];
      /** Points */
      points: components["schemas"]["MetricSeriesPointOut"][];
      /** Time Range */
      time_range: string;
    };
    /** MetricSeriesPointOut */
    MetricSeriesPointOut: {
      /**
       * Observed On
       * Format: date
       */
      observed_on: string;
      /** Sample Size */
      sample_size: number;
      /** Session Id */
      session_id: string | null;
      source_status: components["schemas"]["SourceStatus"];
      /** Value */
      value: number;
    };
    /** MetricSummaryOut */
    MetricSummaryOut: {
      definition: components["schemas"]["MetricDefinitionOut"];
      latest: components["schemas"]["MetricValue"];
      record: components["schemas"]["PersonalRecordOut"] | null;
      window: components["schemas"]["MetricComparison"];
    };
    /**
     * MetricValue
     * @description A number that always travels with its unit and its evidence.
     */
    MetricValue: {
      /** Observed On */
      observed_on?: string | null;
      /**
       * Sample Size
       * @default 0
       */
      sample_size: number;
      source_status?: components["schemas"]["SourceStatus"] | null;
      /** Unit */
      unit: string;
      /** Value */
      value: number | null;
    };
    /** PersonalRecordEventOut */
    PersonalRecordEventOut: {
      /**
       * Achieved On
       * Format: date
       */
      achieved_on: string;
      /** Delta */
      delta: number | null;
      /** Display Precision */
      display_precision: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Metric Display Name */
      metric_display_name: string;
      /** Metric Key */
      metric_key: string;
      /** New Value */
      new_value: number;
      /** Player Display Name */
      player_display_name: string;
      /**
       * Player Id
       * Format: uuid
       */
      player_id: string;
      /** Previous Value */
      previous_value: number | null;
      /** Sample Size */
      sample_size: number;
      source_status: components["schemas"]["SourceStatus"];
      /** Unit */
      unit: string;
    };
    /** PersonalRecordOut */
    PersonalRecordOut: {
      /**
       * Achieved On
       * Format: date
       */
      achieved_on: string;
      /** Display Precision */
      display_precision: number;
      /**
       * Is Manual Override
       * @default false
       */
      is_manual_override: boolean;
      /** Metric Display Name */
      metric_display_name: string;
      /** Metric Key */
      metric_key: string;
      /** Sample Size */
      sample_size: number;
      /** Session Id */
      session_id: string | null;
      source_status: components["schemas"]["SourceStatus"];
      /** Unit */
      unit: string;
      /** Value */
      value: number;
    };
    /** PlayerOverviewOut */
    PlayerOverviewOut: {
      last_session: components["schemas"]["SessionOut"] | null;
      /** Metrics */
      metrics: components["schemas"]["MetricSummaryOut"][];
      player: components["schemas"]["PlayerSummary"];
      /** Sessions In Window */
      sessions_in_window: number;
      /** Time Range */
      time_range: string;
    };
    /** PlayerSummary */
    PlayerSummary: {
      /** Active */
      active: boolean;
      /** Bats */
      bats?: string | null;
      /** Display Name */
      display_name: string;
      /** First Name */
      first_name: string;
      /** Full Name */
      full_name: string;
      /** Graduation Year */
      graduation_year?: number | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Last Name */
      last_name: string;
      /** Position */
      position?: string | null;
      /** Preferred Name */
      preferred_name?: string | null;
      /** Throws */
      throws?: string | null;
    };
    /**
     * RecordDirection
     * @description Which direction of change counts as a personal record.
     * @enum {string}
     */
    RecordDirection: "HIGHER_IS_BETTER" | "LOWER_IS_BETTER" | "NONE";
    /**
     * ResolveIdentityIn
     * @description Attach an unknown vendor athlete to one of our players.
     *
     *     `player_id` is required and explicit: there is no "match by name" option,
     *     by design.
     */
    ResolveIdentityIn: {
      /** Note */
      note?: string | null;
      /**
       * Player Id
       * Format: uuid
       */
      player_id: string;
      /**
       * Reprocess
       * @default true
       */
      reprocess: boolean;
    };
    /**
     * ResolveIdentityOut
     * @description What a mapping actually recovered.
     */
    ResolveIdentityOut: {
      /** Imports Reprocessed */
      imports_reprocessed: number;
      /** New Personal Records */
      new_personal_records: number;
      player: components["schemas"]["PlayerSummary"];
    };
    /**
     * Role
     * @description Platform roles. PARENT is deliberately not implemented yet.
     * @enum {string}
     */
    Role: "ADMIN" | "COACH" | "PLAYER";
    /** SessionOut */
    SessionOut: {
      /**
       * Hit Count
       * @default 0
       */
      hit_count: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Pitch Count
       * @default 0
       */
      pitch_count: number;
      /**
       * Session Date
       * Format: date
       */
      session_date: string;
      /** Session Type */
      session_type?: string | null;
      source_status: components["schemas"]["SourceStatus"];
      /** Started At */
      started_at?: string | null;
      /** Venue */
      venue?: string | null;
      /** Verified At */
      verified_at?: string | null;
    };
    /**
     * SourceStatus
     * @description Confidence level of vendor-supplied data.
     *
     *     TrackMan can publish a session as PRELIMINARY and later republish it as
     *     VERIFIED with corrected values. Everything derived from an event carries the
     *     status of the data it was derived from so the UI can label it honestly.
     * @enum {string}
     */
    SourceStatus: "PRELIMINARY" | "VERIFIED";
    /** SyncJobOut */
    SyncJobOut: {
      /** Attempt Count */
      attempt_count: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Destination */
      destination: string;
      /** Destination Field */
      destination_field: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Last Error */
      last_error: string | null;
      /** Metric Display Name */
      metric_display_name: string;
      /** Metric Key */
      metric_key: string;
      /** Player Display Name */
      player_display_name: string;
      /**
       * Player Id
       * Format: uuid
       */
      player_id: string;
      status: components["schemas"]["SyncStatus"];
      /** Unit */
      unit: string;
      /** Value */
      value: number;
    };
    /**
     * SyncStatus
     * @enum {string}
     */
    SyncStatus: "PENDING" | "SYNCED" | "FAILED" | "MANUAL_REQUIRED";
    /**
     * TimeRange
     * @description Windows the dashboards offer.
     * @enum {string}
     */
    TimeRange: "today" | "7d" | "30d" | "90d" | "1y" | "all";
    /** TodaySnapshotOut */
    TodaySnapshotOut: {
      /** Athletes Trained */
      athletes_trained: number;
      /** New Personal Records */
      new_personal_records: number;
      /**
       * On Date
       * Format: date
       */
      on_date: string;
      /** Sessions */
      sessions: number;
      /** Tracked Events */
      tracked_events: number;
    };
    /** UnresolvedIdentityOut */
    UnresolvedIdentityOut: {
      /** External Display Name */
      external_display_name: string | null;
      /** External Id */
      external_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Last Seen At */
      last_seen_at: string | null;
      /** Occurrence Count */
      occurrence_count: number;
      /** Provider */
      provider: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  today_api_v1_dashboard_today_get: {
    parameters: {
      query?: {
        date?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TodaySnapshotOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_unresolved_api_v1_identity_unresolved_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnresolvedIdentityOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  resolve_identity_api_v1_identity_unresolved__item_id__resolve_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveIdentityIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResolveIdentityOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_imports_api_v1_imports_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_trackman_csv_api_v1_imports_trackman_csv_post: {
    parameters: {
      query?: {
        force?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_trackman_csv_api_v1_imports_trackman_csv_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportResultOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_import_api_v1_imports__import_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        import_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportDetailOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reprocess_import_api_v1_imports__import_id__reprocess_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        import_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportResultOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  integration_status_api_v1_integrations_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IntegrationHealthOut"];
        };
      };
    };
  };
  get_me_api_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
    };
  };
  my_overview_api_v1_me_overview_get: {
    parameters: {
      query?: {
        range?: components["schemas"]["TimeRange"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlayerOverviewOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_records_api_v1_me_prs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalRecordOut"][];
        };
      };
    };
  };
  my_sessions_api_v1_me_sessions_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_metrics_api_v1_metrics_get: {
    parameters: {
      query?: {
        enabled_only?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetricDefinitionOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_players_api_v1_players_get: {
    parameters: {
      query?: {
        /** @description name search: first, last or preferred */
        q?: string | null;
        active_only?: boolean;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlayerSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_player_api_v1_players__player_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        player_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlayerSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_metric_series_api_v1_players__player_id__metrics__metric_key__series_get: {
    parameters: {
      query?: {
        range?: components["schemas"]["TimeRange"];
      };
      header?: never;
      path: {
        player_id: string;
        metric_key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetricSeriesOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_overview_api_v1_players__player_id__overview_get: {
    parameters: {
      query?: {
        range?: components["schemas"]["TimeRange"];
        headline_only?: boolean;
      };
      header?: never;
      path: {
        player_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlayerOverviewOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_personal_records_api_v1_players__player_id__prs_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        player_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalRecordOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_record_history_api_v1_players__player_id__prs__metric_key__history_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        player_id: string;
        metric_key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalRecordEventOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_sessions_api_v1_players__player_id__sessions_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path: {
        player_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  recent_records_api_v1_prs_recent_get: {
    parameters: {
      query?: {
        days?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalRecordEventOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_sessions_api_v1_sessions_get: {
    parameters: {
      query?: {
        date?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pending_futures_updates_api_v1_sync_futures_pending_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncJobOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mark_updated_api_v1_sync_futures__job_id__mark_updated_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncJobOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthOut"];
        };
      };
    };
  };
}
