/**
 * API types, derived from the backend's own OpenAPI document.
 *
 * `api-types.ts` is generated by `pnpm gen:api` from
 * `packages/shared/openapi.json`, which the backend writes with
 * `python -m bsa.scripts.dump_openapi`. CI regenerates both and fails on a diff,
 * so a backend schema change that nobody propagated shows up as a red build
 * rather than as a runtime surprise in the browser.
 *
 * This file exists to give those generated shapes the names the UI actually
 * uses. It must contain aliases only -- never a hand-written field, which is
 * exactly the drift this setup removes.
 */

import type { components } from "@/lib/api-types";

type Schemas = components["schemas"];

// -- identity ---------------------------------------------------------------

export type CurrentUser = Schemas["CurrentUser"];
export type PlayerSummary = Schemas["PlayerSummary"];
export type UnresolvedIdentity = Schemas["UnresolvedIdentityOut"];
export type ResolveIdentityResult = Schemas["ResolveIdentityOut"];
export type CreatePlayerInput = Schemas["CreatePlayerIn"];
export type Role = Schemas["Role"];

/** Whether a value may still change when TrackMan republishes its session. */
export type SourceStatus = Schemas["SourceStatus"];
export type RecordDirection = Schemas["RecordDirection"];
export type ImportStatus = Schemas["ImportStatus"];
export type SyncStatus = Schemas["SyncStatus"];

// -- metrics ----------------------------------------------------------------

export type TimeRange = Schemas["TimeRange"];
export type MetricDefinition = Schemas["MetricDefinitionOut"];
export type MetricValue = Schemas["MetricValue"];
export type MetricComparison = Schemas["MetricComparison"];
export type MetricSummary = Schemas["MetricSummaryOut"];
export type MetricSeries = Schemas["MetricSeriesOut"];
export type MetricSeriesPoint = Schemas["MetricSeriesPointOut"];
export type PersonalRecord = Schemas["PersonalRecordOut"];
export type PersonalRecordEvent = Schemas["PersonalRecordEventOut"];

// -- sessions and overview --------------------------------------------------

export type TrainingSession = Schemas["SessionOut"];
export type PlayerOverview = Schemas["PlayerOverviewOut"];

// -- operations -------------------------------------------------------------

export type TodaySnapshot = Schemas["TodaySnapshotOut"];
export type IntegrationHealth = Schemas["IntegrationHealthOut"];
export type SyncJob = Schemas["SyncJobOut"];
export type ImportSummary = Schemas["ImportOut"];
export type ImportDetail = Schemas["ImportDetailOut"];
export type ImportIssue = Schemas["ImportIssueOut"];
export type ImportResult = Schemas["ImportResultOut"];

export interface ApiErrorBody {
  error: { code: string; message: string };
}
